FROM centos:7

RUN touch /etc/yum.repos.d/td.repo
RUN echo "[treasuredata]" >> /etc/yum.repos.d/td.repo
RUN echo "name=TreasureData" >> /etc/yum.repos.d/td.repo
RUN echo "baseurl=http://packages.treasuredata.com/3/redhat/\$releasever/\$basearch" >> /etc/yum.repos.d/td.repo
RUN echo "gpgcheck=0" >> /etc/yum.repos.d/td.repo
RUN echo "gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent" >> /etc/yum.repos.d/td.repo
RUN yum install -y td-agent nano java-1.8.0-openjdk java-1.8.0-openjdk-devel wget

WORKDIR /opt/
RUN wget https://www.apache.org/dist/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz

RUN tar -xf /opt/apache-tomcat-8.5.50.tar.gz -C /opt/
RUN rm -rf /opt/apache-tomcat-8.5.50.tar.gz
#RUN rm -rf /opt/apache-tomcat-8.5.50/webapps/*

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk/
RUN export JAVA_HOME

#COPY app.jar /opt/apache-tomcat-8.5.50/webapps/

EXPOSE 8080
CMD /etc/init.d/td-agent start && /opt/apache-tomcat-8.5.50/bin/catalina.sh run
